name: mtforum
description: MT论坛第三方客户端
publish_to: 'none'
version: 2.46.10+165

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.7.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  shared_preferences: ^2.3.3
  html: ^0.15.4
  html_unescape: ^2.0.0
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  pull_to_refresh: ^2.0.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  photo_view: ^0.15.0
  file_picker: ^8.1.7
  path_provider: ^2.1.5

  qr_flutter: ^4.1.0

  image_picker: ^1.1.2

  image: ^4.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
